add new static camera mode
TAMS-Group/camera_positioner pull request #7
Opened 2019-12-18 18:07 UTC by lianghongzhuo

add new static camera mode

2019-12-20 08:03 UTC, v4hn requested changes
Your patch changes about every single line of formatting for no obvious reason.
Usually, you should keep the formatting style of the existing code instead!

The commits are also not clean, in the sense that, e.g., the first commit that "changes formatting" also introduces a new `arg` to the launch files.

Lastly, the logic does not make much sense (see inline comment).

The code was never very nice, but we really should try not to make it worse. :)

2019-12-20 08:03 UTC, v4hn commented on src/camera_positioner.cpp
> +                                    initialized = "fixed_mode";
The name `initialized` does not make sense anymore if you store the operation mode here.
Should probably be `state` or `mode` instead.

2019-12-20 08:03 UTC, v4hn commented on src/camera_positioner.cpp
> +                                    initialized = "moraml_mode";
"moraml"?

2019-12-20 08:03 UTC, v4hn commented on src/camera_positioner.cpp
> +            br.sendTransform(tf::StampedTransform(world_camera_transform, ros::Time::now(), "/world", camera_link));
For your new "fixed" mode, publishing the transform in the callback means you have to receive apriltag detection messages *constantly* in order to publish your known values (and ignore the messages).
That does not make sense at all.

In your mode, you should instead shutdown the subscriber altogether (also to show you do not use the values)
and instead spawn an `std::thread` that publishes the transform at a fixed frequency as long as `ros::ok()`.

2019-12-20 16:46 UTC, lianghongzhuo commented
@v4hn Thank you for your review, I will try to update the code.

2019-12-20 17:43 UTC, lianghongzhuo commented
@v4hn I updated the code as your comment except for the code indent. 
As the current code has a mixed code indent (2 and 3 spaces). So I make these indent consistently with 4 spaces.

2019-12-21 09:47 UTC, lianghongzhuo commented
after call sub.shutdow() tf is not publish anymore, even if I write a thread, strange

2021-04-24 08:55 UTC, closed without merging